# https://docs.powersync.com/self-hosting/installation/powersync-service-setup#powersync-configuration
replication:
  connections:
    - type: postgresql
      uri: postgresql://lifter:lifter@db:5432/lifter

      # SSL settings
      sslmode: disable # 'verify-full' (default) or 'verify-ca' or 'disable'

# Connection settings for sync bucket storage
storage:
  type: mongodb
  uri: mongodb://mongo:27017/lifter

# The port which the PowerSync API server will listen on
port: 8080

# Specify sync rules
sync_rules:
  path: sync_rules.yaml

# Settings for client authentication
client_auth:
  # Points to NestJS backend JWKS endpoint
  jwks_uri: http://host.docker.internal:3000/api/.well-known/jwks.json

  # JWKS audience
  audience: ["powersync-dev", "powersync"]

  # Settings for telemetry reporting
  # See https://docs.powersync.com/self-hosting/telemetry
  telemetry:
    # Opt out of reporting anonymized usage metrics to PowerSync telemetry service
    disable_telemetry_sharing: false
