services:
  db:
    image: postgres:18-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=lifter
      - POSTGRES_PASSWORD=lifter
      - POSTGRES_DB=lifter
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "lifter"]
      interval: 2s
      timeout: 2s
      retries: 2

  ttl-cache:
    image: redis:8.4-alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 2
    volumes:
      - redis_data:/data

  migrate:
    build:
      context: ../backend
      dockerfile: Dockerfile.migrate
    environment:
      - DATABASE_URL=postgresql://lifter:lifter@db:5432/lifter
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
