# https://hub.docker.com/_/postgres
services:
  db-test:
    image: postgres:18-alpine
    restart: always

    shm_size: 128mb
    environment:
      POSTGRES_USER: lifter_test
      POSTGRES_PASSWORD: lifter_test
      POSTGRES_DB: lifter_test

    ports:
      - 5434:5432

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "lifter_test"]
      interval: 2s
      timeout: 2s
      retries: 2
